const appStrings = {
  en: {
    pressReset:
      'Please press the reset button if you have recently filled the herbicide tank.',
    shareUsage: 'Share robot usage logs with Dandy Technology',
    shareImages:
      'Share images collected from the robot camera to improve our weed and boundary detection',
    uploadImage: 'Upload Images',
    shareImage: 'Share images collected from the robot camera',
    helpImprove: 'Help improve our weed and boundary detection',
    dataCollection: 'Data Collection',
    turnOn: 'Turn On',
    pleaseEnable: 'Please enable Location Services for use in the app',
    selectNetwork: 'Select Robot Network',
    connectionErr: "Couldn't connect to wifi",
    connectToDandy: 'Connect To Dandy',
    connect: 'Connect',
    cancel: 'Cancel',
    connectToWifi: 'Connect To Wifi',
    ssidNotAccepted: 'SSID (Wifi name) and password combination not accepted',
    weedRemover: 'Weed Remover',
    weedConfidenceLvl: 'Weed Confidence Level',
    default: 'Default',
    picky: 'Very picky',
    close: 'Close',
    sprayFungi: 'Spray Fungicide',
    enableSpraying:
      'Enable for spraying mushrooms instead of weeds, ensure the robot tank is filled with fungicide before enabling',
    uploadLogs: 'Upload Logs',
    ignoreVision: 'Ignore vision boundaries',
    robotWillUseGPS:
      'Robot will use GPS and bumpers only to find yard boundaries',
    theftTracking: 'Theft Tracking',
    theftRecovery: 'Recover from a potential theft by saving robot location',
    weedconfiadjustment: 'Weed confidence adjustment',
    adjustPicky: 'Adjust how picky the robot is in spraying weeds',
    robotUpdate: 'Robot Software Update',
    checkNapply: 'Check for and apply new updates',
    editID: 'Edit Product ID',
    editProductID:
      'Change Product ID to re-connect to a robot on your home Wifi',
    save: 'Save',
    yourproductID: 'Your current product ID is',
    noDevice: 'No Device Connected',
    robotStatus: 'Robot Status',
    dandyapp: 'Dandy App',
    version: 'Version',
    deviceName: 'Device Name',
    batteryHealth: 'Battery Health',
    checkLocation: 'Check Robot Location',
    taptocheck: 'Tap to check on the robot',
    spray_level: 'Spray Level',
    deviceID: 'Device ID',
    status: 'Status',
    type: 'Type',
    ipaddress: 'IP Address',
    back: 'Back',
    robotInfo: 'Robot Information',
    groundCoverd: 'Ground Covered',
    location: 'Location',
    live: 'Live',
    charging: 'Charging',
    pluggedin: 'Plugged In',
    disconnected: 'Disconnected',
    dandyrobot: 'Dandy Robot',
    registration: 'Product Registration',
    registrationSubtitle:
      'Registering will help deliver better customer care, updates, and assist in tracking robot in case of theft.',
    registrationfailed: "Couldn't register, Please try again",
    dataCollectionSub:
      'Allow data collection to help us improve your user experience',
    robotName: 'Robot Name',
    robotNameSub: 'Please enter a new name for the robot',
    locationService: 'Location services',
    connectRobot: 'Connect Robot',
    connectRobotSub:
      'When your robot appears below, tap to start connecting your robot to your Wi-Fi. Searching for available robots...',
    connectRobotSubwifi:
      'Your Dandy Robot will be connected to your Wi-Fi Network.',
    emailErrorTex: 'Please enter a valid email',
    factoryResetTitle: 'Factory Reset',
    factoryResetSubTitle:
      'Reset your robots data including network selection and geofencing history',
    editNameTitle: 'Edit Robot Name',
    editNameSubTitle: 'Change robot name to a new name',
    currentDistance: 'Current Distance',
    lifetimeDistance: 'Lifetime Distance',
    currentSprays: 'Current Sprays',
    lifetimeSprays: 'Lifetime Sprays',
  },
};

export default appStrings;
